changelog:
  exclude:
    labels:
      - ignore
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Enhancements 🎉
      labels:
        - enhancement
    - title: Bug Fixes 🐛
      labels:
        - bug
    - title: Testing
      labels:
        - testing
    - title: Build & CI
      labels:
        - ci
    - title: Documentation
      labels:
        - documentation
    - title: IDE
      labels:
        - ide
    - title: Other Changes
      labels:
        - "*"
