apiVersion: kude.kfirs.com/v1alpha1
kind: Pipeline
resources:
  - resources.yaml
pipeline:
  - image: ghcr.io/arikkfir/kude/functions/label
    config:
      name: fromFile
      path: value.txt
    mounts:
      - value.txt
  - image: ghcr.io/arikkfir/kude/functions/label
    config:
      name: numeric
      value: "123"
  - image: ghcr.io/arikkfir/kude/functions/label
    config:
      name: string
      value: "abc"
