apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: test
  name: test
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: test
  template:
    metadata:
      labels:
        app.kubernetes.io/component: test
    spec:
      containers:
        - image: test/test
          name: server
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: helm-remote-chart-podinfo
    app.kubernetes.io/version: 6.1.0
    helm.sh/chart: podinfo-6.1.0
  name: helm-remote-chart-podinfo
spec:
  ports:
    - name: http
      port: 9898
      protocol: TCP
      targetPort: http
    - name: grpc
      port: 9999
      protocol: TCP
      targetPort: grpc
  selector:
    app.kubernetes.io/name: helm-remote-chart-podinfo
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: helm-remote-chart-podinfo
    app.kubernetes.io/version: 6.1.0
    helm.sh/chart: podinfo-6.1.0
  name: helm-remote-chart-podinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: helm-remote-chart-podinfo
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "9898"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: helm-remote-chart-podinfo
    spec:
      containers:
        - command:
            - ./podinfo
            - --port=9898
            - --cert-path=/data/cert
            - --port-metrics=9797
            - --grpc-port=9999
            - --grpc-service-name=podinfo
            - --level=info
            - --random-delay=false
            - --random-error=false
          env:
            - name: PODINFO_UI_COLOR
              value: '#34577c'
          image: ghcr.io/stefanprodan/podinfo:6.1.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - podcli
                - check
                - http
                - localhost:9898/healthz
            initialDelaySeconds: 1
            timeoutSeconds: 5
          name: podinfo
          ports:
            - containerPort: 9898
              name: http
              protocol: TCP
            - containerPort: 9797
              name: http-metrics
              protocol: TCP
            - containerPort: 9999
              name: grpc
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - podcli
                - check
                - http
                - localhost:9898/readyz
            initialDelaySeconds: 1
            timeoutSeconds: 5
          resources:
            limits: null
            requests:
              cpu: 1m
              memory: 16Mi
          volumeMounts:
            - mountPath: /data
              name: data
      nodeSelector:
        purpose: podinfo
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: data
