apiVersion: kude.kfirs.com/v1alpha1
kind: Scenario
go:
  package: main
package:
  apiVersion: kude.kfirs.com/v1alpha1
  kind: Package
  resources:
    - resources.yaml
  pipeline:
    - image: ghcr.io/arikkfir/kude/functions/set-namespace
      config:
        namespace: test
        includes:
          - apiVersion: v1
            kind: ServiceAccount
    - image: ghcr.io/arikkfir/kude/functions/set-namespace
      config:
        namespace: error
        includes:
          - apiVersion: v1
            kind: UnknownKind

resources:
  resources.yaml: |-
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: t1
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: test
    spec:
      selector:
        app: MyApp
      ports:
        - protocol: TCP
          port: 80
          targetPort: 9376

expected: |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: t1
    namespace: test
  ---
  apiVersion: v1
  kind: Service
  metadata:
    name: test
  spec:
    ports:
      - port: 80
        protocol: TCP
        targetPort: 9376
    selector:
      app: MyApp
