apiVersion: kude.kfirs.com/v1alpha1
kind: Scenario
package:
  apiVersion: kude.kfirs.com/v1alpha1
  kind: Package
  resources:
    - service-account.yaml
  pipeline:
    - image: ghcr.io/arikkfir/kude/functions/annotate
      config:
        name: numeric
        value: "123"
    - image: ghcr.io/arikkfir/kude/functions/annotate
      config:
        name: string
        value: "abc"

resources:
  service-account.yaml: |-
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: test

expected: |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      numeric: "123"
      string: abc
    name: test
