apiVersion: kude.kfirs.com/v1alpha1
kind: Scenario
package:
  apiVersion: kude.kfirs.com/v1alpha1
  kind: Package
  resources:
    - service-account.yaml
  pipeline:
    - image: ghcr.io/arikkfir/kude/functions/annotate
      config:
        name: ann
        path: value.txt
      mounts:
        - value.txt

resources:
  value.txt: stored in a file
  service-account.yaml: |-
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: test

expected: |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      ann: stored in a file
    name: test
