apiVersion: kude.kfirs.com/v1alpha1
kind: Scenario
package:
  apiVersion: kude.kfirs.com/v1alpha1
  kind: Package
  resources:
    - resources.yaml

resources:
  resources.yaml: |+
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app.kubernetes.io/component: test
      name: test
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/component: test
      template:
        metadata:
          labels:
            app.kubernetes.io/component: test
        spec:
          containers:
            - image: test/test
              name: server
              ports: [ { containerPort: 8080,name: http,protocol: TCP } ]

expected: |+
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app.kubernetes.io/component: test
    name: test
  spec:
    selector:
      matchLabels:
        app.kubernetes.io/component: test
    template:
      metadata:
        labels:
          app.kubernetes.io/component: test
      spec:
        containers:
          - image: test/test
            name: server
            ports:
              - containerPort: 8080
                name: http
                protocol: TCP
