apiVersion: kude.kfirs.com/v1alpha1
kind: Scenario
package:
  apiVersion: kude.kfirs.com/v1alpha1
  kind: Package
  resources:
    - resources.yaml
  pipeline:
    - image: ghcr.io/arikkfir/kude/functions/annotate
      config:
        name: foo
        value: bar
    - image: ghcr.io/arikkfir/kude/functions/label
      config:
        name: foo
        value: bar

resources:
  resources.yaml: |+
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: test
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/component: test
      template:
        metadata:
          labels:
            app.kubernetes.io/component: test
        spec:
          containers:
            - image: test/test
              name: server

expected: |+
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      foo: bar
    labels:
      foo: bar
    name: test
  spec:
    selector:
      matchLabels:
        app.kubernetes.io/component: test
    template:
      metadata:
        labels:
          app.kubernetes.io/component: test
      spec:
        containers:
          - image: test/test
            name: server
