name: Functions CI
on:
  push:
    branches: [ "*" ]
    paths:
      - .github/workflows/ci-functions.yml
      - functions/**
defaults:
  run:
    shell: bash -eu {0}
jobs:
  discover-functions:
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    outputs:
      functions: ${{ steps.discover.outputs.functions }}
    steps:
      - uses: actions/checkout@v2
      - id: discover
        run: echo "::set-output name=functions::$(ls -d * | jq -R -s -c 'split("\n")[:-1]')"
        working-directory: functions
  build:
    runs-on: ubuntu-20.04
    needs: [ discover-functions ]
    strategy:
      matrix:
        function: ${{fromJson(needs.discover-functions.outputs.functions)}}
    timeout-minutes: 15
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t ghcr.io/arikkfir/kude/functions/${{ matrix.function }}:${{ github.sha }} .
        working-directory: functions/${{ matrix.function }}
      - run: docker tag ghcr.io/arikkfir/kude/functions/${{ matrix.function }}:${{ github.sha }} ghcr.io/arikkfir/kude/functions/${{ matrix.function }}:${GITHUB_SHA::7}
      - run: |
          docker push ghcr.io/arikkfir/kude/functions/${{ matrix.function }}:${{ github.sha }}
          docker push ghcr.io/arikkfir/kude/functions/${{ matrix.function }}:${GITHUB_SHA::7}
      - if: ${{ github.ref }} == "refs/heads/main"
        run: |
          docker tag ghcr.io/arikkfir/kude/functions/${{ matrix.function }}:${{ github.sha }} ghcr.io/arikkfir/kude/functions/${{ matrix.function }}:latest
          docker push ghcr.io/arikkfir/kude/functions/${{ matrix.function }}:latest
