name: Release
on:
  release:
    types:
      - created
      - edited
  push:
    tags: [ v* ]
defaults:
  run:
    shell: bash -eu {0}
jobs:
  cli:
    name: Tag CLI ${{ matrix.os }}
    runs-on: ubuntu-20.04
    steps:
      - uses: google-github-actions/auth@v0
        with:
          service_account: kude-github-actions@arikkfir.iam.gserviceaccount.com
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: google-github-actions/setup-gcloud@v0
      - run: gsutil cp gs://arikkfir-artifacts/kude/kude-${{ matrix.os }}-${{ github.sha }} ./kude-${{ matrix.os }}
      - run: gh release upload --clobber ${{ github.ref_name }} ./kude-${{ matrix.os }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        os: [ darwin, linux ]
