name: Tag
on:
  push:
    tags: [ v* ]
defaults:
  run:
    shell: bash -eu {0}
# TODO: detect if most recent release and tag as latest
jobs:
  discover-functions:
    outputs:
      functions: ${{ steps.discover.outputs.functions }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - id: discover
        run: echo "::set-output name=functions::$(ls -d * | jq -R -s -c 'split("\n")[:-1]')"
        working-directory: functions
  tag-functions:
    name: Tag function ${{ matrix.function }}
    needs: [ discover-functions ]
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-20.04
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: docker-meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/arikkfir/kude/functions/${{ matrix.function }}
          tags: |
            type=schedule,enabled=false
            type=semver,pattern={{version}}
            type=semver,pattern=v{{major}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=tag
      - run: |-
          docker pull ${IMAGE}
          TAGS="${{ steps.docker-meta.outputs.tags }}"
          for tag in ${TAGS}; do
            docker tag ${IMAGE} ${tag}
            docker push ${tag}
          done
        env:
          IMAGE: ghcr.io/arikkfir/kude/functions/${{ matrix.function }}:${{ github.sha }}
    strategy:
      matrix:
        function: ${{fromJson(needs.discover-functions.outputs.functions)}}
