name: Tag
on:
  push:
    tags: [ v* ]
defaults:
  run:
    shell: bash -eu {0}
jobs:
  tag-functions:
    name: Tag function ${{ matrix.function }}
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-20.04
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: docker-meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/arikkfir/kude/functions/${{ matrix.function }}
          tags: |
            type=schedule,enabled=false
            type=semver,pattern={{version}}
            type=semver,pattern=v{{major}}
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=tag
      - run: |-
          TAGS="${{ steps.docker-meta.outputs.tags }}"
          for tag in ${TAGS}; do
            echo docker tag ${IMAGE} ${tag}
            echo docker push ${tag}
          done
        env:
          IMAGE: ghcr.io/arikkfir/kude/functions/${{ matrix.function }}:${{ github.sha }}
    strategy:
      matrix:
        function: [ annotate ]
